//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Adocao = new HashSet<Adocao>();
            this.AnuncioEvento = new HashSet<AnuncioEvento>();
            this.Comunicacao = new HashSet<Comunicacao>();
        }
    
        public int Id_Anuncio { get; set; }
        public int Fk_Usuario { get; set; }
        public int Fk_Animal { get; set; }
        public int Fk_TipoAnuncio { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adocao> Adocao { get; set; }
        public virtual Animal Animal { get; set; }
        public virtual TipoAnuncio TipoAnuncio { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuncioEvento> AnuncioEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comunicacao> Comunicacao { get; set; }
    }
}
