//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuncioEvento
    {
        public int Id_AnuncioEvento { get; set; }
        public int Fk_Evento { get; set; }
        public int Fk_Anuncio { get; set; }
    
        public virtual Anuncio Anuncio { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
