//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adocao> Adocao { get; set; }
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Anuncio> Anuncio { get; set; }
        public virtual DbSet<AnuncioEvento> AnuncioEvento { get; set; }
        public virtual DbSet<Comunicacao> Comunicacao { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<TipoAnuncio> TipoAnuncio { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
